spring.application.name=oblak

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

oblak.zip.max-total-extracted-size-bytes=104857600
oblak.zip.max-files=1000

oblak.temp-dir-name=temp
oblak.minio.bucket=projects

oblak.ext4.image-min-size-bytes=67108864
oblak.ext4.image-extra-size-bytes=268435456
oblak.firecracker.kernel-path=src/main/resources/firecracker/images/vmlinux-6.1.155
oblak.firecracker.rootfs-path=src/main/resources/firecracker/images/ubuntu-24.04.ext4
oblak.firecracker.fetch-script-path=src/main/resources/firecracker/scripts/fetch-kernel-rootfs.sh
oblak.firecracker.max-execution-time-seconds=120
oblak.firecracker.max-preparation-time-seconds=300
oblak.firecracker.network.enabled=true
oblak.firecracker.network.host-dev-name=tap0
oblak.firecracker.network.guest-mac=06:00:ac:10:00:02
oblak.firecracker.network.guest-ip=172.16.0.2
oblak.firecracker.network.guest-cidr-prefix=24
oblak.firecracker.network.guest-gateway=172.16.0.1
oblak.firecracker.network.dns-server=1.1.1.1

jwt.secret=1UDIQ3QYqdc0o26Sp6xHT1h5lol2EIvy3MykCBKoyRZxxtQa31K7TxEPi7JIXe9cH3WNoKyFIo331AxpKQ64wg==
jwt.expiration-ms=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/oblak
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
