spring.application.name=oblak

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

oblak.zip.max-total-extracted-size-bytes=104857600
oblak.zip.max-files=1000

oblak.temp-dir-name=temp
oblak.minio.bucket=projects

oblak.ext4.image-min-size-bytes=1048576
oblak.ext4.image-extra-size-bytes=1048576
oblak.firecracker.kernel-path=src/main/resources/firecracker/images/vmlinux-6.1.155
oblak.firecracker.rootfs-path=src/main/resources/firecracker/images/ubuntu-24.04.ext4
oblak.firecracker.fetch-script-path=src/main/resources/firecracker/scripts/fetch-kernel-rootfs.sh
oblak.firecracker.max-execution-time-seconds=120

jwt.secret=1UDIQ3QYqdc0o26Sp6xHT1h5lol2EIvy3MykCBKoyRZxxtQa31K7TxEPi7JIXe9cH3WNoKyFIo331AxpKQ64wg==
jwt.expiration-ms=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/oblak
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
