spring.application.name=oblak

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

oblak.zip.max-total-extracted-size-bytes=104857600
oblak.zip.max-files=1000

oblak.temp-dir-name=temp
oblak.minio.bucket=projects

oblak.ext4.image-min-size-bytes=1048576
oblak.ext4.image-extra-size-bytes=1048576
